version: '3.7'
services:
  postgres:
    image: 'postgres:15.3'
    environment:
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=admin
    ports:
      - '5432:5432'

